import { useEffect, useState } from 'react';
import Head from 'next/head';
import { Box } from '@mui/material';
import { Air, Timelapse, WaterDrop } from '@mui/icons-material';

import { axios } from '@/config';
import { AQInfoCard, Header, HistoryTemperatureChart, InfoCard, Temperature } from '@/components';
import { APIResponse, Datum } from '@/interfaces';

export default function Home() {
  const [data, setData] = useState<Datum[]>([]);

  useEffect(() => {
    axios.get<APIResponse>('/api/v2/list')
      .then(res => { setData(res.data.data); });
  }, []);

  return (
    <>
      <Head>
        <title>Proyecto Final Redes</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        component='main'
        sx={{ width: '100vw', height: '100vh', overflow: 'auto', padding: '30px 100px' }}
      >
        <Box sx={{ width: '100%' }}>
          <Header
            city={data.at(0)?.city ?? ''}
            country={data.at(0)?.country ?? ''}
            datetime={data.at(0)?.datetime ?? ''}
          />
          <Box
            sx={{
              display: 'flex',
              justifyContent: 'space-between',
              marginTop: '30px',
              gap: '120px'
            }}
          >
            <Temperature
              code={data.at(0)?.weather.code ?? 0}
              temp={data.at(0)?.weather.temp ?? 0}
              feels_like={data.at(0)?.weather.feels_like ?? 0}
            />
            <Box
              sx={{
                flex: 1,
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'center',
                alignItems: 'center',
                gap: '20px'
              }}
            >
              <InfoCard
                title='Humedad'
                value={data.at(0)?.weather.humidity + ' %'}
                icon={<WaterDrop sx={{ color: '#444444' }} />}
              />
              <InfoCard
                title='Presión'
                value={data.at(0)?.weather.pressure + ' hPa'}
                icon={<Timelapse sx={{ color: '#444444' }} />}
              />
              <InfoCard
                title='Viento'
                value={data.at(0)?.wind.speed + ' m/s'}
                icon={<Air sx={{ color: '#444444' }} />}
              />
            </Box>
          </Box>
          <Box
            sx={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              margin: '60px',
              gap: '20px'
            }}
          >
            <AQInfoCard title='CO' value={data.at(0)?.aq.co} />
            <AQInfoCard title='O3' value={data.at(0)?.aq.o3} color='#36BCBA' />
            <AQInfoCard title='PM 2.5' value={data.at(0)?.aq.pm2_5} color='#F65606' />
            <AQInfoCard title='NO2' value={data.at(0)?.aq.no2} color='#304C89' />
            <AQInfoCard
              title='GAS'
              value={data.at(0)?.gas === 0 ? 'Bueno' : 'Malo'}
              color='#DB5461'
              units={false}
            />
          </Box>
          <HistoryTemperatureChart data={data} />
        </Box>
      </Box>
    </>
  )
}
