// Generated by https://quicktype.io

export interface APIResponse {
    data:    Datum[];
    message: string;
    ok:      boolean;
    status:  number;
}

export interface Datum {
    _id:      string;
    aq:       { [key: string]: number };
    city:     string;
    country:  string;
    datetime: string;
    gas:      number;
    weather:  Weather;
    wind:     Wind;
}

export interface Weather {
    code:       number;
    feels_like: number;
    humidity:   number;
    pressure:   number;
    temp:       number;
    temp_max:   number;
    temp_min:   number;
}

export interface Wind {
    deg:   number;
    speed: number;
}
